# Generated by Django 4.1.1 on 2022-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pizza", options={"verbose_name_plural": "pizza"},
        ),
        migrations.AlterModelOptions(
            name="size", options={"verbose_name_plural": "size"},
        ),
        migrations.AlterField(
            model_name="pizza", name="topping2", field=models.CharField(max_length=100),
        ),
    ]
